<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entities\Reservation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'checkIn' => [parent::class, 'checkIn', null, 16],
        "\0".parent::class."\0".'checkOut' => [parent::class, 'checkOut', null, 16],
        "\0".parent::class."\0".'guest' => [parent::class, 'guest', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'room' => [parent::class, 'room', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'totalPrice' => [parent::class, 'totalPrice', null, 16],
        'checkIn' => [parent::class, 'checkIn', null, 16],
        'checkOut' => [parent::class, 'checkOut', null, 16],
        'guest' => [parent::class, 'guest', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'room' => [parent::class, 'room', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'totalPrice' => [parent::class, 'totalPrice', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
